version: "3.6"
services:
  educator:
    image: educator:local
    container_name: educator
    ports:
      - "8081:80"
    environment:
      DJANGO_SETTINGS: "educator.settings"
    networks:
      - site
    volumes:
      - db_data:/app/db

volumes:
  db_data:

networks:
  site:
    driver: bridge
    external: true
