# Generated by Django 3.0.5 on 2020-05-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отправитель')),
                ('text', models.TextField(verbose_name='Текст')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='e-mail')),
            ],
        ),
    ]
