# Generated by Django 3.0.5 on 2020-05-06 15:26

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержимое')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, max_length=1000, populate_from='title', unique_with=('title',), verbose_name='Короткое имя')),
                ('display', models.BooleanField(default=True, verbose_name='Отображение')),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
    ]
