# Generated by Django 3.0.5 on 2020-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0002_auto_20200506_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
