# Generated by Django 3.0.5 on 2020-05-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0003_page_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя изображения')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Картинка галлереи',
                'verbose_name_plural': 'Картинки галлереи',
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
