# Generated by Django 3.0.5 on 2020-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0004_auto_20200510_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
    ]
