# Generated by Django 3.0.5 on 2020-05-10 17:06

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0005_galleryphoto_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('iframe_code', models.TextField(verbose_name='Код html')),
                ('link', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, max_length=1000, populate_from='name', unique_with=('name',), verbose_name='Короткое имя')),
            ],
        ),
    ]
