# Generated by Django 3.0.5 on 2020-05-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0006_cloudfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educator.Page', verbose_name='Страница отображения'),
        ),
    ]
