# Generated by Django 3.0.5 on 2020-05-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0007_cloudfile_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudfile',
            options={'verbose_name': 'Облачный файл', 'verbose_name_plural': 'Облачные файлы'},
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educator.Page', verbose_name='Страница отображения'),
        ),
    ]
